// Auto-generated by dynamic_regress/run_pipeline.py.
// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.
// generated_at: 2026-04-28T17:52:20
// robot_name: 05_urdf
// data_source: real
// real_torque_source: sensed
// parameterization: base
// identification_mode: rigid_body_friction
// payload_mode: none
// nonlinear_compensation: disabled_for_export
#pragma once

#include "hic_common_types.h"
#include "hic_controller/dynamics/hic_dynamics_base.h"

using namespace KDL;

class sevendofDynamics : public dynamicsBase
{
public:
	sevendofDynamics();
	virtual ~sevendofDynamics();

	virtual void setRobotDHParameters
	(
		const EcRealVector& kinematcisParam
	);

	virtual void setGravityVector
	(
		const EcReal gx, const EcReal gy, const EcReal gz
	);

	virtual void calculateGravityJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	// 完整估计扭矩接口：
	// 默认使用类内部识别参数，只使用外部设置的重力方向。
	// 只有显式打开 setUseExternalRuntimeParms(true) 后，才允许使用外部 parms。
	virtual EcBoolean calculateEstimateJointToqrues
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	void setUseExternalRuntimeParms
	(
		const EcBoolean useExternalParms
	);

	void computeRigidTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeMassTorque
	(
		const EcRealVector& q,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeCoriolisTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		EcRealVector& tau
	) const;

	void computeGravityAxisTorques
	(
		const EcRealVector& q,
		EcRealVector& tauGxUnit,
		EcRealVector& tauGyUnit,
		EcRealVector& tauGzUnit
	) const;

	void computeFrictionTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeInverseDynamics
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	virtual void calculateMomentumEstimatedJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

private:
	static const EcSizeT kNumJoints = 7;
	static const EcSizeT kRigidParamsPerJoint = 10;
	static const EcSizeT kRuntimeParamsPerJoint = 13;
	EcSizeT m_NumJoints;
	EcReal m_gx;
	EcReal m_gy;
	EcReal m_gz;
	// 外部参数总开关：
	// false 时，sevendofDynamics 默认只使用内部固定参数；
	// true 时，若调用处传入了合法 parms，则允许使用外部参数重建扭矩。
	EcBoolean m_useExternalRuntimeParms;
	EcRealVector m_zeros;
	// 代码生成阶段固化到类内的默认动力学参数。
	// 当前 7轴模型的“本地参数”都保存在这里。
	EcRealVector m_defaultParms;

	bool hasValidRuntimeParms(const EcRealVector& parms) const;
	// 根据当前策略选择“真正参与计算的参数”：
	// 外部参数为空时回退到内部默认参数；外部参数不空时使用外部参数。
	// 注意：是否允许走到外部参数，还要受 m_useExternalRuntimeParms 控制。
	const EcRealVector& activeRuntimeParms(const EcRealVector& parms) const;
	void computeTorqueFromRegressor
	(
		const double* regressor,
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcBoolean includeMotorInertia,
		EcBoolean includeFriction,
		EcRealVector& tau
	) const;
};
